cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: api-astral

spring:
  servelet:
    multipart:
      enabled: true
      file-size-threshold: 3MB
      max-file-size: 3MB
      max-request-size: 10MB

server:
  port: 8080